name: CI
on:
  push:
    branches:
      - testnet/3
  pull_request:
    branches:
      - testnet/3
jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: Install OpenCL
        run: sudo apt-get update && sudo apt-get install -y mesa-opencl-icd ocl-icd-opencl-dev jq make
      - name: Check out code
        uses: actions/checkout@v1
      - name: Test
        run: make test

  docker:
    name: Docker publishing
    runs-on: self-hosted
    needs: Test
    steps:
      - name: Publish
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: textileio/lotus-devnet
          tag_with_ref: true
          tag_with_sha: true
